-- Campus Crib V8: in-app messaging, voice-call signaling and chat notifications.
-- Run after the existing V6/V7 migrations.

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  property_id uuid references public.properties(id) on delete set null,
  kind text not null default 'listing' check (kind in ('listing','support')),
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.conversation_members (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  last_read_at timestamptz,
  primary key (conversation_id, user_id)
);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 5000),
  created_at timestamptz not null default now()
);

create index if not exists idx_conversation_members_user on public.conversation_members(user_id);
create index if not exists idx_messages_conversation_created on public.messages(conversation_id, created_at);
create index if not exists idx_conversations_property on public.conversations(property_id);

create table if not exists public.voice_calls (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  caller_id uuid not null references public.profiles(id) on delete cascade,
  callee_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'ringing' check (status in ('ringing','active','ended','declined','missed')),
  started_at timestamptz,
  ended_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.voice_call_signals (
  id bigint generated by default as identity primary key,
  call_id uuid not null references public.voice_calls(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  signal_type text not null check (signal_type in ('offer','answer','ice-candidate','hangup')),
  payload jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_voice_calls_conversation on public.voice_calls(conversation_id, created_at desc);
create index if not exists idx_voice_signals_call on public.voice_call_signals(call_id, id);


create or replace function public.is_conversation_member(p_conversation_id uuid, p_user_id uuid default auth.uid())
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (select 1 from public.conversation_members cm where cm.conversation_id = p_conversation_id and cm.user_id = p_user_id);
$$;
grant execute on function public.is_conversation_member(uuid,uuid) to authenticated;

alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;
alter table public.voice_calls enable row level security;
alter table public.voice_call_signals enable row level security;

-- Conversation visibility follows membership. Admins may see support/listing
-- conversations for moderation and support work.
drop policy if exists "Conversation members can view conversations" on public.conversations;
create policy "Conversation members can view conversations"
  on public.conversations for select to authenticated
  using (public.is_admin() or public.is_conversation_member(id, auth.uid()));

drop policy if exists "Conversation members can view members" on public.conversation_members;
create policy "Conversation members can view members"
  on public.conversation_members for select to authenticated
  using (public.is_admin() or public.is_conversation_member(conversation_id, auth.uid()));

drop policy if exists "Members can view messages" on public.messages;
create policy "Members can view messages"
  on public.messages for select to authenticated
  using (public.is_conversation_member(messages.conversation_id, auth.uid()) or public.is_admin());

drop policy if exists "Members can send messages" on public.messages;
create policy "Members can send messages"
  on public.messages for insert to authenticated
  with check (sender_id = auth.uid() and public.is_conversation_member(conversation_id, auth.uid()));

drop policy if exists "Call participants can view calls" on public.voice_calls;
create policy "Call participants can view calls"
  on public.voice_calls for select to authenticated
  using (caller_id = auth.uid() or callee_id = auth.uid() or public.is_admin());

drop policy if exists "Conversation members can create calls" on public.voice_calls;
create policy "Conversation members can create calls"
  on public.voice_calls for insert to authenticated
  with check (
    caller_id = auth.uid()
    and public.is_conversation_member(voice_calls.conversation_id, auth.uid())
    and public.is_conversation_member(voice_calls.conversation_id, voice_calls.callee_id)
  );

drop policy if exists "Call participants can update calls" on public.voice_calls;
create policy "Call participants can update calls"
  on public.voice_calls for update to authenticated
  using (caller_id = auth.uid() or callee_id = auth.uid() or public.is_admin())
  with check (caller_id = auth.uid() or callee_id = auth.uid() or public.is_admin());

drop policy if exists "Call participants can view signals" on public.voice_call_signals;
create policy "Call participants can view signals"
  on public.voice_call_signals for select to authenticated
  using (exists (
    select 1 from public.voice_calls vc where vc.id = call_id and (vc.caller_id = auth.uid() or vc.callee_id = auth.uid() or public.is_admin())
  ));

drop policy if exists "Call participants can send signals" on public.voice_call_signals;
create policy "Call participants can send signals"
  on public.voice_call_signals for insert to authenticated
  with check (sender_id = auth.uid() and exists (
    select 1 from public.voice_calls vc where vc.id = call_id and (vc.caller_id = auth.uid() or vc.callee_id = auth.uid())
  ));

-- Prevent clients from changing conversation ownership/participants directly.
revoke insert, update, delete on public.conversations from authenticated;
revoke insert, update, delete on public.conversation_members from authenticated;

create or replace function public.start_listing_conversation(p_property_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_property public.properties%rowtype;
  v_conversation uuid;
  v_landlord uuid;
begin
  if auth.uid() is null then raise exception 'You must be logged in'; end if;
  select * into v_property from public.properties where id = p_property_id and status = 'approved';
  if not found then raise exception 'Listing not found or not approved'; end if;
  v_landlord := v_property.landlord_id;

  if not (public.is_admin() or auth.uid() = v_landlord or public.has_property_access(p_property_id, auth.uid())) then
    raise exception 'Listing contact access has not been approved';
  end if;

  select c.id into v_conversation
  from public.conversations c
  where c.property_id = p_property_id and c.kind = 'listing'
    and exists (select 1 from public.conversation_members cm where cm.conversation_id = c.id and cm.user_id = auth.uid())
    and exists (select 1 from public.conversation_members cm where cm.conversation_id = c.id and cm.user_id = v_landlord)
  order by c.created_at desc limit 1;

  if v_conversation is null then
    insert into public.conversations(property_id, kind, created_by) values (p_property_id, 'listing', auth.uid()) returning id into v_conversation;
    insert into public.conversation_members(conversation_id, user_id) values (v_conversation, auth.uid()) on conflict do nothing;
    insert into public.conversation_members(conversation_id, user_id) values (v_conversation, v_landlord) on conflict do nothing;
  end if;
  return v_conversation;
end;
$$;
grant execute on function public.start_listing_conversation(uuid) to authenticated;

create or replace function public.start_support_conversation()
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_conversation uuid;
  v_admin uuid;
begin
  if auth.uid() is null then raise exception 'You must be logged in'; end if;
  select id into v_admin from public.profiles where role = 'admin' order by created_at asc limit 1;
  if v_admin is null then raise exception 'Campus Crib support is not configured yet'; end if;

  select c.id into v_conversation
  from public.conversations c
  where c.kind = 'support' and c.property_id is null
    and exists (select 1 from public.conversation_members cm where cm.conversation_id = c.id and cm.user_id = auth.uid())
    and exists (select 1 from public.conversation_members cm where cm.conversation_id = c.id and cm.user_id = v_admin)
  order by c.created_at desc limit 1;

  if v_conversation is null then
    insert into public.conversations(kind, created_by) values ('support', auth.uid()) returning id into v_conversation;
    insert into public.conversation_members(conversation_id, user_id) values (v_conversation, auth.uid()) on conflict do nothing;
    insert into public.conversation_members(conversation_id, user_id) values (v_conversation, v_admin) on conflict do nothing;
  end if;
  return v_conversation;
end;
$$;
grant execute on function public.start_support_conversation() to authenticated;

-- Message notifications are created server-side, so users cannot forge them.
create or replace function public.notify_new_chat_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  recipient uuid;
  v_sender text;
begin
  select coalesce(name, 'Campus Crib user') into v_sender from public.profiles where id = new.sender_id;
  for recipient in
    select cm.user_id from public.conversation_members cm
    where cm.conversation_id = new.conversation_id and cm.user_id <> new.sender_id
  loop
    insert into public.notifications(user_id, message, type)
    values (recipient, left(v_sender || ': ' || new.body, 500), 'chat_message');
  end loop;
  update public.conversations set updated_at = now() where id = new.conversation_id;
  return new;
end;
$$;

drop trigger if exists messages_notify_recipient on public.messages;
create trigger messages_notify_recipient
after insert on public.messages for each row execute function public.notify_new_chat_message();

-- Call ringing/ending also creates normal in-app notifications. Existing
-- push-notification trigger will forward these to subscribed devices.
create or replace function public.notify_voice_call_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.notifications(user_id, message, type)
    values (new.callee_id, 'Incoming Campus Crib voice call. Open Messages to answer.', 'voice_call');
  elsif new.status = 'ended' and old.status <> 'ended' then
    insert into public.notifications(user_id, message, type)
    values (case when auth.uid() = new.caller_id then new.callee_id else new.caller_id end, 'A Campus Crib voice call has ended.', 'voice_call');
  end if;
  return new;
end;
$$;

drop trigger if exists voice_calls_notify_event on public.voice_calls;
create trigger voice_calls_notify_event
after insert or update on public.voice_calls for each row execute function public.notify_voice_call_event();

-- Realtime feeds for chat and call signaling.
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'conversations') then
    alter publication supabase_realtime add table public.conversations;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'conversation_members') then
    alter publication supabase_realtime add table public.conversation_members;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'messages') then
    alter publication supabase_realtime add table public.messages;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'voice_calls') then
    alter publication supabase_realtime add table public.voice_calls;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'voice_call_signals') then
    alter publication supabase_realtime add table public.voice_call_signals;
  end if;
end $$;

-- Chat/call tables contain private conversations; keep them out of the
-- anon role entirely.
revoke all on public.conversations, public.conversation_members, public.messages, public.voice_calls, public.voice_call_signals from anon;
grant select on public.conversations, public.conversation_members, public.messages, public.voice_calls, public.voice_call_signals to authenticated;
grant insert on public.messages, public.voice_calls, public.voice_call_signals to authenticated;
grant update on public.voice_calls to authenticated;

-- Make push notifications open the relevant area when the app is installed/opened.
-- This replaces the generic root URL used by the older V27 trigger while preserving
-- its safe no-op behavior when push dispatch isn't configured.
create or replace function public.push_notification_on_insert()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_url text;
  v_key text;
  v_target text := '/';
begin
  begin
    v_url := current_setting('app.settings.supabase_url', true);
    v_key := current_setting('app.settings.service_role_key', true);
    if new.type in ('chat_message', 'voice_call') then v_target := '/messages'; end if;
    if v_url is null or v_key is null or v_url = '' or v_key = '' then return new; end if;
    perform net.http_post(
      url := v_url || '/functions/v1/send-push-notification',
      headers := jsonb_build_object('Content-Type', 'application/json', 'Authorization', 'Bearer ' || v_key),
      body := jsonb_build_object('user_id', new.user_id, 'title', case when new.type = 'voice_call' then 'Campus Crib call' else 'Campus Crib' end, 'body', new.message, 'url', v_target)
    );
  exception when others then null;
  end;
  return new;
end;
$$;
